#path: C:\Users\EbruSaraBagca\PycharmProjects\YOLOv8-CustomObjectDetection\dataset
#train: images/train
#val: images/validation
path: /content/drive/MyDrive/plate_detect_data
train: train_data
val: val_detect

# Classes ss
names:
  0: uc
